### ISSUE TITLE
Thảo luận đồ án

### ISSUE THREAD

**Issue by nguyenhuands99** [nguyenhuands99/p4ds-final-project#1]
Mình đã hoàn thành xong đồ án và rất mong nhận được sự góp ý của của các bạn.  If I make any kind of mistakes, please correct me! Thanks a lot!

**Comment by ngocbinh53** [comment]
Chào bạn,
Đoạn code script thứ 37, bạn có nhận xét là lúc bạn nhận xét năm 2018 tụt dốc mạnh do hết dẽ liệu thì liệu mình có các nào cho nó dừng luôn tại tháng10 mà không vẽ tiếp không nhỉ, hoặc mình biểu diễn 5 năm trong 1 biểu đồ để so sánh tháng 1-10, còn tháng 11-12 sẽ so sánh riêng, theo mình như vậy sẽ dễ nhìn hơn. 
Đoạn code script 43: viet_res_df_sub có vài dòng hours là {'Monday': '0:0-0:0', }, mình không hiể 0:0-0:0 đây là nguyên 1 ngày từ 0 sáng đến 0h tối hay không mở cửa.
Mình có một chút thắc mắc vậy, mong bạn giải đáp.
Cảm ơn bạn.

**Comment by nguyenhuands99** [comment]
Hi @ngocbinh53 ,
Cảm ơn bạn đã góp ý. Mình trả lời câu sau trước hours: {'Monday': '0:0-0:0',...} tức là hôm đó nghỉ nha bạn 😄 thời gian trong ngày từ 0:0 đến 23:59.
Còn dữ liệu dừng ở tháng 11-2018 dẫn đến việc đồ thị tụt xuống mình nghĩ chỉ cần giải thích lý do là được. Nếu tách riêng thành 2 đồ thị để đảm bảo độ đồng nhất trong từng đồ thị, mà trade-off là mất tính liên tục trong năm thì chắc mình không đánh đổi. Còn hướng dừng ở tháng 10-2018 là một ý kiến hay, mình sẽ update sau.
Thanks 😁
